apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy10
  labels:
    app: autodeploy10
  namespace: lab04-workflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy10
  template:
    metadata:
      labels:
        app: autodeploy10
    spec:
      containers:
        - name: autodeploy10
          image: acrworkflow1708548952606.azurecr.io/image-workflow-1708548952606:latest
          ports:
            - containerPort: 5000