apiVersion: v1
kind: Service
metadata:
  name: autodeploy10
  namespace: lab04-workflow
spec:
  type: LoadBalancer
  selector:
    app: autodeploy10
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000